"use client";
import { FormEvent, useState } from "react";
import SectionHeading from "./SectionHeading";
import { CONTACT_EMAIL, CONTACT_PHONE, WHATSAPP_NUMBER } from "@/lib/constants";

export default function ContactForm(){
const [ok,setOk]=useState(false);const [errors,setErrors]=useState<Record<string,string>>({});
function onSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const name=String(fd.get('name')||'').trim();const email=String(fd.get('email')||'').trim();const sector=String(fd.get('sector')||'').trim();const message=String(fd.get('message')||'').trim();const ne:Record<string,string>={};if(!name)ne.name='Nombre requerido';if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))ne.email='Correo válido requerido';if(!sector)ne.sector='Selecciona un sector';if(!message)ne.message='Mensaje requerido';setErrors(ne);if(Object.keys(ne).length===0){setOk(true);e.currentTarget.reset();/* TODO: conectar API/email/CRM/WhatsApp */}}
const waLink=WHATSAPP_NUMBER?`https://wa.me/${WHATSAPP_NUMBER}`:"";
return <section id="contacto" className="py-20 bg-white"><div className="mx-auto max-w-4xl px-4"><SectionHeading title="Contacto" description="Cuéntanos qué producto necesitas proteger y bajo qué condiciones debe conservarse. Te ayudamos a encontrar una solución térmica adecuada para tu operación." center/><form onSubmit={onSubmit} noValidate className="mt-10 grid gap-4 rounded-3xl border border-brand-lightAlt p-6 md:grid-cols-2">{[['name','Nombre*'],['company','Empresa'],['email','Correo*'],['phone','Teléfono']].map(([n,l])=><label key={n} className="text-sm font-semibold text-brand-blue">{l}<input name={n} type={n==='email'?'email':'text'} className="mt-1 w-full rounded-xl border border-brand-lightSoft px-3 py-2"/>{errors[n]&&<span className="text-xs text-brand-red">{errors[n]}</span>}</label>)}<label className="text-sm font-semibold text-brand-blue md:col-span-2">Sector*<select name="sector" className="mt-1 w-full rounded-xl border border-brand-lightSoft px-3 py-2"><option value="">Selecciona</option><option>Farmacéutico</option><option>Veterinario</option><option>Alimentos</option><option>Cosméticos</option></select>{errors.sector&&<span className="text-xs text-brand-red">{errors.sector}</span>}</label><label className="text-sm font-semibold text-brand-blue md:col-span-2">Mensaje*<textarea name="message" rows={4} className="mt-1 w-full rounded-xl border border-brand-lightSoft px-3 py-2"/>{errors.message&&<span className="text-xs text-brand-red">{errors.message}</span>}</label><div className="md:col-span-2 flex flex-wrap gap-3 items-center"><button className="rounded-full bg-brand-red px-6 py-3 font-bold text-white">Enviar solicitud</button>{waLink && <a href={waLink} className="rounded-full border border-brand-blue px-5 py-3 font-semibold text-brand-blue">WhatsApp</a>}</div>{ok&&<p className="md:col-span-2 rounded-xl bg-brand-light p-3 text-brand-blue">Gracias. Hemos recibido tu solicitud. Pronto nos pondremos en contacto contigo.</p>}</form><p className="mt-4 text-sm text-slate-500">Contacto general: {CONTACT_EMAIL||"correo@pendiente.com"} · {CONTACT_PHONE||"+57 pendiente"}</p></div></section>}
